// SPDX-License-Identifier: MIT
// crates/wisp-hud/src/tray.rs
//! The StatusNotifierItem: what a running Wisp looks like when the overlay
//! is all there is to see.
//!
//! Spec 6 §4.2. The tray lives in the HUD because every entry on the menu is
//! something the HUD already has — the latest snapshot, `HudMode.active`, the
//! config path, the socket path — so the mode toggle is a function call and
//! not a fourth binary with a channel to this one.
//!
//! Spec 6 §3.2 is the shape of this file: the D-Bus connection lives on its
//! own thread, the render loop writes one mutex and sends on one channel, and
//! nothing the render loop calls can wait on the bus.

use std::sync::mpsc::{self, Sender};
use std::sync::{Arc, Mutex};

use wisp_proto::Snapshot;

/// 22 px and 48 px, ARGB32 in network byte order, generated by
/// `packaging/render-tray-icon.sh` from `packaging/io.github.jds300.Wisp.svg`.
/// Carried as well as the theme name because an AppImage run out of
/// `~/AppImages` may never have installed the theme icon.
const TRAY_22: &[u8] = include_bytes!("../icons/tray-22.argb");
const TRAY_48: &[u8] = include_bytes!("../icons/tray-48.argb");

/// The SNI item id, and the icon's theme name: the application id, as the
/// desktop entry, the AppImage and the Flatpak all spell it.
const ITEM_ID: &str = "io.github.jds300.Wisp";

/// What the menu shows. Written by the render loop, read by the tray thread.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct TrayState {
    /// `env!("CARGO_PKG_VERSION")`, passed in rather than read here so the
    /// menu model is a pure function of its argument and testable with any
    /// version string.
    pub version: &'static str,
    /// The file name from the snapshot (`Snapshot.log`), or `None` while the
    /// daemon is waiting for a log.
    pub log_name: Option<String>,
    /// `duration_s` of an *active* encounter. A lingering one is not a fight.
    pub fight: Option<u64>,
    pub hud_mode: bool,
}

/// What the user asked for by clicking. Three, because the menu has three
/// things that do something; the status line is disabled and does nothing.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TrayEvent {
    ToggleHudMode,
    OpenConfig,
    Stop,
}

/// The menu, as data: everything that decides what the tray draws, and
/// nothing about how it is drawn. Pure, so Milestone 5's "TrayState -> menu
/// text and check state" is a unit test and not a click.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MenuModel {
    /// The status line, e.g. `Wisp 0.3.0 · eqlog_Daggo_freeport.txt · idle`.
    pub status: String,
    pub hud_mode_checked: bool,
}

pub fn menu_model(state: &TrayState) -> MenuModel {
    let log = state.log_name.as_deref().unwrap_or("waiting for a log");
    let fight = match state.fight {
        Some(seconds) => format!("fighting {seconds} s"),
        None => "idle".to_string(),
    };
    MenuModel {
        status: format!("Wisp {} · {log} · {fight}", state.version),
        hud_mode_checked: state.hud_mode,
    }
}

/// A `TrayState` from one snapshot and the HUD's own mode flag.
pub fn tray_state(version: &'static str, snapshot: &Snapshot, hud_mode: bool) -> TrayState {
    TrayState {
        version,
        log_name: snapshot.log.clone(),
        // Only an active encounter is a fight: the panel lingers after one
        // ends, and a tray that said "fighting" for a dead mob would be lying.
        fight: snapshot.encounter.as_ref().filter(|e| e.active).map(|e| e.duration_s),
        hud_mode,
    }
}

/// Doubles every `_`. dbusmenu reads a single underscore in a label as a
/// mnemonic marker and does not draw it, which would turn
/// `eqlog_Daggo_freeport.txt` into `eqlogDaggofreeport.txt` on screen.
pub fn escape_mnemonics(text: &str) -> String {
    text.replace('_', "__")
}

/// The tray item itself. Holds no state of its own: the render loop owns
/// `TrayState` behind the mutex and the tray reads it, so publishing a new
/// state is one assignment and never a D-Bus round trip.
pub struct WispTray {
    state: Arc<Mutex<TrayState>>,
    events: Sender<TrayEvent>,
}

impl WispTray {
    /// A copy of the state to build a menu from. A poisoned mutex means the
    /// render loop panicked while holding it, in which case the HUD is on its
    /// way down and a default menu for one frame is the right answer.
    fn snapshot(&self) -> TrayState {
        self.state.lock().map(|s| s.clone()).unwrap_or_default()
    }

    fn send(&self, event: TrayEvent) {
        // The render loop is the receiver; if it is gone, so is the HUD.
        let _ = self.events.send(event);
    }
}

fn icon(width: i32, data: &[u8]) -> ksni::Icon {
    ksni::Icon { width, height: width, data: data.to_vec() }
}

impl ksni::Tray for WispTray {
    fn id(&self) -> String {
        ITEM_ID.to_string()
    }

    fn title(&self) -> String {
        "Wisp".to_string()
    }

    fn category(&self) -> ksni::Category {
        ksni::Category::ApplicationStatus
    }

    fn status(&self) -> ksni::Status {
        ksni::Status::Active
    }

    fn icon_name(&self) -> String {
        ITEM_ID.to_string()
    }

    fn icon_pixmap(&self) -> Vec<ksni::Icon> {
        vec![icon(22, TRAY_22), icon(48, TRAY_48)]
    }

    /// Left click. The SNI convention is that `Activate` runs the item's
    /// primary action, and the mode toggle is the only one of the three that
    /// is harmless to hit twice.
    fn activate(&mut self, _x: i32, _y: i32) {
        self.send(TrayEvent::ToggleHudMode);
    }

    fn menu(&self) -> Vec<ksni::MenuItem<Self>> {
        use ksni::menu::{CheckmarkItem, StandardItem};
        let model = menu_model(&self.snapshot());
        vec![
            StandardItem {
                label: escape_mnemonics(&model.status),
                enabled: false,
                ..Default::default()
            }
            .into(),
            CheckmarkItem {
                label: "HUD mode".to_string(),
                checked: model.hud_mode_checked,
                // The checkbox is not toggled here: the render loop decides
                // whether HUD mode may be entered (§4.7's refusal when the
                // layout failed to parse), and the state it publishes is what
                // the box shows on the next update.
                activate: Box::new(|tray: &mut Self| tray.send(TrayEvent::ToggleHudMode)),
                ..Default::default()
            }
            .into(),
            StandardItem {
                label: "Open config".to_string(),
                activate: Box::new(|tray: &mut Self| tray.send(TrayEvent::OpenConfig)),
                ..Default::default()
            }
            .into(),
            StandardItem {
                label: "Stop Wisp".to_string(),
                activate: Box::new(|tray: &mut Self| tray.send(TrayEvent::Stop)),
                ..Default::default()
            }
            .into(),
        ]
    }
}

pub struct TrayHandle {
    state: Arc<Mutex<TrayState>>,
    /// Wakes the updater thread. Unbounded, so a send is never a wait.
    nudge: Sender<()>,
    /// What the menu last showed, so the bus is only told about real changes
    /// and not about every one of the twenty frames a second the HUD draws.
    last: MenuModel,
}

impl TrayHandle {
    /// Publish a new state.
    ///
    /// Never blocks: the mutex is held for one assignment, and the D-Bus
    /// update happens on the updater thread. Spec 6 §3.2.
    pub fn publish(&mut self, next: TrayState) {
        let model = menu_model(&next);
        if let Ok(mut slot) = self.state.lock() {
            *slot = next;
        }
        if model != self.last {
            self.last = model;
            let _ = self.nudge.send(());
        }
    }
}

/// Start the tray on its own thread.
///
/// `None`, after one `wisp-hud: no tray: <reason>` line on stderr, when
/// there is no session bus, no `org.kde.StatusNotifierWatcher` on it, or no
/// host to show the item (gamescope game mode, `Xvfb` in CI). The HUD then
/// runs exactly as it did in v0.2.0.
pub fn spawn_tray(state: Arc<Mutex<TrayState>>, events: Sender<TrayEvent>) -> Option<TrayHandle> {
    use ksni::blocking::TrayMethods as _;

    let initial = state.lock().map(|s| menu_model(&s)).unwrap_or_else(|_| menu_model(&TrayState::default()));
    let tray = WispTray { state: Arc::clone(&state), events };
    // In a Flatpak the sandbox gives the app a unique bus name and nothing
    // else, so owning the specification's `StatusNotifierItem-PID-ID`
    // well-known name fails unless the manifest also carries an `--own-name`.
    // Spec §4.2 adds exactly one `finish-args` line and no more, so the
    // adjustment is made here instead: ksni's own escape hatch, which its
    // documentation names Flatpak as the reason for. Outside a Flatpak the
    // name is owned as the specification asks.
    let sandboxed = std::env::var_os("FLATPAK_ID").is_some();
    let handle = match tray.disable_dbus_name(sandboxed).spawn() {
        Ok(handle) => handle,
        // No session bus, no watcher on it, or a watcher with no host to show
        // the item: all three are one line and a HUD that carries on.
        Err(e) => {
            eprintln!("wisp-hud: no tray: {e}");
            return None;
        }
    };

    let (nudge, wake) = mpsc::channel();
    // The updater thread exists so `publish` cannot wait on the bus:
    // `Handle::update` blocks until the service has emitted its property and
    // layout signals, and that is a socket write this thread can afford and
    // the render loop cannot. The closure is empty because the tray reads the
    // state through the mutex; `update` re-reads `Tray::menu` and diffs it.
    std::thread::Builder::new()
        .name("wisp-tray".to_string())
        .spawn(move || {
            // Ends when the render loop drops the TrayHandle, which is when
            // the HUD is exiting anyway.
            while wake.recv().is_ok() {
                if handle.update(|_tray| {}).is_none() {
                    // The service shut down; nothing more to update.
                    break;
                }
            }
        })
        .ok()?;

    Some(TrayHandle { state, nudge, last: initial })
}

#[cfg(test)]
mod tests {
    use super::*;
    use wisp_proto::{Encounter, Personal, Snapshot, PROTOCOL_VERSION};

    fn state() -> TrayState {
        TrayState {
            version: "0.3.0",
            log_name: Some("eqlog_Daggo_freeport.txt".to_string()),
            fight: None,
            hud_mode: false,
        }
    }

    #[test]
    fn the_status_line_names_the_version_the_log_and_the_fight() {
        assert_eq!(
            menu_model(&state()).status,
            "Wisp 0.3.0 · eqlog_Daggo_freeport.txt · idle"
        );
        let fighting = TrayState { fight: Some(42), ..state() };
        assert_eq!(menu_model(&fighting).status, "Wisp 0.3.0 · eqlog_Daggo_freeport.txt · fighting 42 s");
    }

    #[test]
    fn no_log_reads_waiting_for_a_log() {
        let waiting = TrayState { log_name: None, ..state() };
        assert_eq!(menu_model(&waiting).status, "Wisp 0.3.0 · waiting for a log · idle");
    }

    #[test]
    fn the_checkbox_mirrors_hud_mode() {
        assert!(!menu_model(&state()).hud_mode_checked);
        assert!(menu_model(&TrayState { hud_mode: true, ..state() }).hud_mode_checked);
    }

    #[test]
    fn underscores_are_doubled_so_dbusmenu_draws_them() {
        // A single underscore is a mnemonic marker and is not drawn at all,
        // which would turn the log's own name into nonsense.
        assert_eq!(escape_mnemonics("eqlog_Daggo_freeport.txt"), "eqlog__Daggo__freeport.txt");
        assert_eq!(escape_mnemonics("HUD mode"), "HUD mode");
        assert_eq!(escape_mnemonics(""), "");
    }

    fn snapshot(log: Option<&str>, encounter: Option<Encounter>) -> Snapshot {
        Snapshot {
            v: PROTOCOL_VERSION,
            seq: 1,
            ts: String::new(),
            log: log.map(str::to_string),
            lines_ingested: 0,
            session_kills: 0,
            timers: Vec::new(),
            encounter,
        }
    }

    fn fight(active: bool, duration_s: u64) -> Encounter {
        Encounter {
            active,
            duration_s,
            you: Personal { damage: 0, dps: 0, taken: 0, taken_ps: 0, healing: 0, hps: 0, overheal: 0 },
            damage: Vec::new(),
            healing: Vec::new(),
        }
    }

    #[test]
    fn a_snapshot_becomes_a_tray_state_and_a_lingering_fight_is_not_one() {
        let s = tray_state("0.3.0", &snapshot(Some("eqlog_Daggo_freeport.txt"), Some(fight(true, 42))), true);
        assert_eq!(s.log_name.as_deref(), Some("eqlog_Daggo_freeport.txt"));
        assert_eq!(s.fight, Some(42));
        assert!(s.hud_mode);

        let lingering = tray_state("0.3.0", &snapshot(Some("x.txt"), Some(fight(false, 42))), false);
        assert_eq!(lingering.fight, None, "a fight that has ended is not a fight");
        assert_eq!(menu_model(&lingering).status, "Wisp 0.3.0 · x.txt · idle");

        let nothing = tray_state("0.3.0", &snapshot(None, None), false);
        assert_eq!((nothing.log_name, nothing.fight), (None, None));
    }
}
